#!/usr/bin/env zsh

echo "Deploying..."

echo "Point to droplet:"
eval $(docker-machine env twocents)

echo "Build:"
docker-compose -f production.docker-compose.yml build

echo "Run:"
docker-compose -f production.docker-compose.yml up -d

echo "Deployed!"
