version: '2.4'
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: healthcheck/postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=twocents
      - POSTGRES_PASSWORD=
      - POSTRES_DB=twocents-database
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: twocents:latest
    ports:
      - 80:3000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/go/src/github.com/chunkhang/twocents/app

