version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: twocents:latest
    tty: true
    environment:
      - PORT=3000
    ports:
      - 80:3000
    volumes:
      - ./:/go/src/github.com/chunkhang/twocents
