version: '3'
services:
  app:
    build:
      context: .
      dockerfile: production.Dockerfile
    image: twocents:latest
    environment:
      - PORT=3000
    ports:
      - 80:3000
    restart: always
